# https://github.com/pypa/setuptools_scm
[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/xyz/_version.py"

# TODO: add ruff config
# https://docs.astral.sh/ruff/configuration/
